spring:
  application:
    name: BlogFunction
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogx?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useUnicode=yes&characterEncoding=utf-8&useSSL=no
    username: root
    password: root


server:
  port: 1002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2001/eureka
#    enabled: false
#  instance:
#    prefer-ip-address: true     #访问路径可以显示IP地址