spring:
  application:
    name: eureka-server

server:
  port: 2001


eureka:
  server:
    enable-self-preservation: false # eureka 的自我保护状态：心跳失败的比例，在15分钟内是否超过85%,如果出现了超过的情况，Eureka Server会将当前的实例注册信息保护起来，同时提示一个警告，一旦进入保护模式，Eureka Server将会尝试保护其服务注册表中的信息，不再删除服务注册表中的数据。也就是不会注销任何微服务
  instance:
    hostname: eureka
  client:
    register-with-eureka: false # 不从自身拉取注册信息
    fetch-registry: false # 不从自身拉取注册信息

